- hosts: all
  become: yes
  tasks:
    - name: create portainer volume
      community.docker.docker_volume:
        name: "portainer_data"
    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"
        restart_policy: always
