- hosts: all
  become: yes
  tasks:
    - name: Install packages/prerequisites "Debian"
      apt:
        name:
          - curl
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - virtualenv
          - python3-setuptools
        state: present
        cache_valid_time: 3600
      when: ansible_facts.os_family == "Debian"

    - name: Install packages on redhatfamily
      yum:
        name:
          - curl
          - python3
          - python3-pip
          - lvm2
          - device-mapper-persistent-data
          - yum-utils
          - device-mapper
          - device-mapper-persistent-data
          - device-mapper-event
          - device-mapper-libs
          - device-mapper-event-libs
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: install python docker SDK
      pip:
        name: docker
